name: Push commit
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git remote -v
          git remote set-url origin https://github.com/smrithigUCI/ActionTrial.git
          git remote -v
          git add report.txt
          git checkout -b master
          git push origin master
