name: Push commit
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: ${{ github.head_ref }}
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config user.name 'smrithigUCI'
          git config user.email 'smrithig@uci.edu'
          git remote set-url origin https://github.com/smrithigUCI/ActionTrial.git
          git add report.txt
          git commit -am "Automated report"
          git push origin HEAD:main
