name: tkInter Screen Script
on: workflow_dispatch
jobs:
   build:
    runs-on: ubuntu-latest
    steps:
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/workflows/requirements.txt
          
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          sudo apt-get install -y xauth
          sudo apt-get install -y tk
      

      - name: Run Tkinter script
        run: |
          export DISPLAY=:99
          xvfb-run python GUINotification.py
